[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["James <jammyw@gmail.com>"]
edition = "2018"

[[bin]]
name = "aoc2019"
path = "src/main.rs"

[dependencies]
structopt = "0.3.5"
itertools = "0.8"
regex = "1.3"
once_cell = "1.2"
num = "0.2.0"
rayon = "1.2.1"
pathfinding = "2.0.3"